<?php

namespace Database\Seeders;

use App\Models\SubDistrict;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class SubDistrictSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $subDistricts = [
            ['district_id' => '1', 'name' => 'ধামরাই'],
            ['district_id' => '1', 'name' => 'দোহার'],
            ['district_id' => '1', 'name' => 'কেরানীগঞ্জ'],
            ['district_id' => '1', 'name' => 'নবাবগঞ্জ'],
            ['district_id' => '1', 'name' => 'সাভার'],
            ['district_id' => '2', 'name' => 'আলফাডাঙ্গা'],
            ['district_id' => '2', 'name' => 'ভাঙ্গা'],
            ['district_id' => '2', 'name' => 'বোয়ালমারী'],
            ['district_id' => '2', 'name' => 'চরভদ্রাসন'],
            ['district_id' => '2', 'name' => 'ফরিদপুর সদর'],
            ['district_id' => '2', 'name' => 'মধুখালী'],
            ['district_id' => '2', 'name' => 'নগরকান্দা'],
            ['district_id' => '2', 'name' => 'সদরপুর'],
            ['district_id' => '2', 'name' => 'সালথা'],
            ['district_id' => '3', 'name' => 'গাজীপুর সদর'],
            ['district_id' => '3', 'name' => 'কালিয়াকৈর'],
            ['district_id' => '3', 'name' => 'কালীগঞ্জ'],
            ['district_id' => '3', 'name' => 'কাপাসিয়া'],
            ['district_id' => '3', 'name' => 'শ্রীপুর'],
            ['district_id' => '4', 'name' => 'গোপালগঞ্জ সদর'],
            ['district_id' => '4', 'name' => 'কাশিয়ানী'],
            ['district_id' => '4', 'name' => 'কোটালীপাড়া'],
            ['district_id' => '4', 'name' => 'মুকসুদপুর'],
            ['district_id' => '4', 'name' => 'টুঙ্গিপাড়া'],
            ['district_id' => '5', 'name' => 'দেওয়ানগঞ্জ'],
            ['district_id' => '5', 'name' => 'ইসলামপুর'],
            ['district_id' => '5', 'name' => 'জামালপুর সদর'],
            ['district_id' => '5', 'name' => 'মাদারগঞ্জ'],
            ['district_id' => '5', 'name' => 'মেলান্দহ'],
            ['district_id' => '5', 'name' => 'সরিষাবাড়ী'],
            ['district_id' => '6', 'name' => 'অষ্টগ্রাম'],
            ['district_id' => '6', 'name' => 'বাজিতপুর'],
            ['district_id' => '6', 'name' => 'ভৈরব'],
            ['district_id' => '6', 'name' => 'হোসেনপুর'],
            ['district_id' => '6', 'name' => 'ইটনা'],
            ['district_id' => '6', 'name' => 'করিমগঞ্জ'],
            ['district_id' => '6', 'name' => 'কটিয়াদি'],
            ['district_id' => '6', 'name' => 'কিশোরগঞ্জ সদর'],
            ['district_id' => '6', 'name' => 'কুলিয়ারচর'],
            ['district_id' => '6', 'name' => 'মিঠামইন'],
            ['district_id' => '6', 'name' => 'নিকলী'],
            ['district_id' => '6', 'name' => 'পাকুন্দিয়া'],
            ['district_id' => '6', 'name' => 'তাড়াইল'],
            ['district_id' => '7', 'name' => 'মাদারীপুর সদর'],
            ['district_id' => '7', 'name' => 'কালকিনি'],
            ['district_id' => '7', 'name' => 'রাজৈর'],
            ['district_id' => '7', 'name' => 'শিবচর'],
            ['district_id' => '8', 'name' => 'মানিকগঞ্জ সদর'],
            ['district_id' => '8', 'name' => 'সিংগাইর'],
            ['district_id' => '8', 'name' => 'শিবালয়'],
            ['district_id' => '8', 'name' => 'সাটুরিয়া'],
            ['district_id' => '8', 'name' => 'হরিরামপুর'],
            ['district_id' => '8', 'name' => 'ঘিওর'],
            ['district_id' => '8', 'name' => 'দৌলতপুর'],
            ['district_id' => '9', 'name' => 'মুন্সীগঞ্জ সদর'],
            ['district_id' => '9', 'name' => 'শ্রীনগর'],
            ['district_id' => '9', 'name' => 'সিরাজদিখান'],
            ['district_id' => '9', 'name' => 'লোহাজং'],
            ['district_id' => '9', 'name' => 'টঙ্গীবাড়ী'],
            ['district_id' => '9', 'name' => 'গজারিয়া'],
            ['district_id' => '10', 'name' => 'ময়মনসিংহ সদর'],
            ['district_id' => '10', 'name' => 'ধোবাউড়া'],
            ['district_id' => '10', 'name' => 'ফুলপুর'],
            ['district_id' => '10', 'name' => 'হালুয়াঘাট'],
            ['district_id' => '10', 'name' => 'গৌরীপুর'],
            ['district_id' => '10', 'name' => 'গফরগাঁও'],
            ['district_id' => '10', 'name' => 'ঈশ্বরগঞ্জ'],
            ['district_id' => '10', 'name' => 'নন্দাইল'],
            ['district_id' => '10', 'name' => 'ত্রিশাল'],

            ['district_id' => '11', 'name' => 'আড়াইহাজার'],
            ['district_id' => '11', 'name' => 'বন্দর'],
            ['district_id' => '11', 'name' => 'নারায়ণগঞ্জ সদর'],
            ['district_id' => '11', 'name' => 'রূপগঞ্জ'],
            ['district_id' => '11', 'name' => 'সোনারগাঁ'],
            ['district_id' => '12', 'name' => 'বেলাবো'],
            ['district_id' => '12', 'name' => 'মনোহরদী'],
            ['district_id' => '12', 'name' => 'নরসিংদী সদর'],
            ['district_id' => '12', 'name' => 'পলাশ'],
            ['district_id' => '12', 'name' => 'রায়পুরা'],
            ['district_id' => '12', 'name' => 'শিবপুর'],
            ['district_id' => '13', 'name' => 'আটপাড়া'],
            ['district_id' => '13', 'name' => 'বরহাট্টা'],
            ['district_id' => '13', 'name' => 'দুর্গাপুর'],
            ['district_id' => '13', 'name' => 'খালিয়াজুরী'],
            ['district_id' => '13', 'name' => 'কলমাকান্দা'],
            ['district_id' => '13', 'name' => 'কেন্দুয়া'],
            ['district_id' => '13', 'name' => 'মদন'],
            ['district_id' => '13', 'name' => 'মোহনগঞ্জ'],
            ['district_id' => '13', 'name' => 'নেত্রকোণা সদর'],
            ['district_id' => '13', 'name' => 'পূর্বধলা'],
            ['district_id' => '14', 'name' => 'বালিয়াকান্দি'],
            ['district_id' => '14', 'name' => 'গোয়ালন্দঘাট'],
            ['district_id' => '14', 'name' => 'পাংশা'],
            ['district_id' => '14', 'name' => 'রাজবাড়ী সদর'],
            ['district_id' => '15', 'name' => 'ভেদরগঞ্জ'],
            ['district_id' => '15', 'name' => 'ডামুড্যা'],
            ['district_id' => '15', 'name' => 'গোসাইরহাট'],
            ['district_id' => '15', 'name' => 'নড়িয়া'],
            ['district_id' => '15', 'name' => 'শরীয়তপুর সদর'],
            ['district_id' => '15', 'name' => 'জাজিরা'],
            ['district_id' => '16', 'name' => 'ঝিনাইগাতী'],
            ['district_id' => '16', 'name' => 'নকলা'],
            ['district_id' => '16', 'name' => 'নালিতাবাড়ী'],
            ['district_id' => '16', 'name' => 'শেরপুর সদর'],
            ['district_id' => '16', 'name' => 'শ্রীবরদী'],
            ['district_id' => '17', 'name' => 'বাসাইল'],
            ['district_id' => '17', 'name' => 'ভুয়াপুর'],
            ['district_id' => '17', 'name' => 'দেলদুয়ার'],
            ['district_id' => '17', 'name' => 'ঘাটাইল'],
            ['district_id' => '17', 'name' => 'গোপালপুর'],
            ['district_id' => '17', 'name' => 'কালিহাতী'],
            ['district_id' => '17', 'name' => 'মধুপুর'],
            ['district_id' => '17', 'name' => 'মির্জাপুর'],
            ['district_id' => '17', 'name' => 'নগরপুর'],
            ['district_id' => '17', 'name' => 'সখিপুর'],
            ['district_id' => '17', 'name' => 'টাঙ্গাইল সদর'],
            ['district_id' => '18', 'name' => 'বগুড়া সদর'],
            ['district_id' => '18', 'name' => 'ধুনট'],
            ['district_id' => '18', 'name' => 'ধূপচাঁচিয়া'],
            ['district_id' => '18', 'name' => 'গাবতলী'],
            ['district_id' => '18', 'name' => 'কাহালু'],
            ['district_id' => '18', 'name' => 'নন্দিগ্রাম'],
            ['district_id' => '18', 'name' => 'সারিয়াকান্দি'],
            ['district_id' => '18', 'name' => 'শাজাহানপুর'],
            ['district_id' => '18', 'name' => 'শেরপুর'],
            ['district_id' => '18', 'name' => 'শিবগঞ্জ'],
            ['district_id' => '18', 'name' => 'সোনাতলা'],
            ['district_id' => '19', 'name' => 'জয়পুরহাট সদর'],
            ['district_id' => '19', 'name' => 'আক্কেলপুর'],
            ['district_id' => '19', 'name' => 'কালাই'],
            ['district_id' => '19', 'name' => 'খেতলাল'],
            ['district_id' => '19', 'name' => 'পাঁচবিবি'],
            ['district_id' => '20', 'name' => 'আত্রাই'],
            ['district_id' => '20', 'name' => 'বদলগাছী'],
            ['district_id' => '20', 'name' => 'মান্দা'],
            ['district_id' => '20', 'name' => 'ধামইরহাট'],
            ['district_id' => '20', 'name' => 'মহাদেবপুর'],
            ['district_id' => '20', 'name' => 'নওগাঁ সদর'],
            ['district_id' => '20', 'name' => 'নিয়ামতপুর'],
            ['district_id' => '20', 'name' => 'পত্নিতলা'],
            ['district_id' => '20', 'name' => 'পোরশা'],
            ['district_id' => '20', 'name' => 'রাণীনগর'],
            ['district_id' => '20', 'name' => 'সাপাহার'],

            ['district_id' => '21', 'name' => 'বাগাতিপাড়া'],
            ['district_id' => '21', 'name' => 'বড়াইগ্রাম'],
            ['district_id' => '21', 'name' => 'গুরুদাসপুর'],
            ['district_id' => '21', 'name' => 'লালপুর'],
            ['district_id' => '21', 'name' => 'নাটোর সদর'],
            ['district_id' => '21', 'name' => 'সিংড়া'],
            ['district_id' => '22', 'name' => 'ভোলাহাট'],
            ['district_id' => '22', 'name' => 'গোমস্তাপুর'],
            ['district_id' => '22', 'name' => 'নাচোল'],
            ['district_id' => '22', 'name' => 'নবাবগঞ্জ সদর'],
            ['district_id' => '22', 'name' => 'শিবগঞ্জ'],
            ['district_id' => '23', 'name' => 'আটঘরিয়া'],
            ['district_id' => '23', 'name' => 'বেড়া'],
            ['district_id' => '23', 'name' => 'ভাঙ্গুড়া'],
            ['district_id' => '23', 'name' => 'চাটমোহর'],
            ['district_id' => '23', 'name' => 'ফরিদপুর'],
            ['district_id' => '23', 'name' => 'ঈশ্বরদী'],
            ['district_id' => '23', 'name' => 'পাবনা সদর'],
            ['district_id' => '23', 'name' => 'সাঁথিয়া'],
            ['district_id' => '23', 'name' => 'সুজানগর'],
            ['district_id' => '24', 'name' => 'বাঘা'],
            ['district_id' => '24', 'name' => 'বাগমারা'],
            ['district_id' => '24', 'name' => 'চারঘাট'],
            ['district_id' => '24', 'name' => 'দুর্গাপুর'],
            ['district_id' => '24', 'name' => 'গোদাগাড়ী'],
            ['district_id' => '24', 'name' => 'মোহনপুর'],
            ['district_id' => '24', 'name' => 'পবা'],
            ['district_id' => '24', 'name' => 'পুঠিয়া'],
            ['district_id' => '24', 'name' => 'তানোর'],
            ['district_id' => '25', 'name' => 'বেলকুচি'],
            ['district_id' => '25', 'name' => 'চৌহালী'],
            ['district_id' => '25', 'name' => 'কামারখন্দ'],
            ['district_id' => '25', 'name' => 'কাজীপুর'],
            ['district_id' => '25', 'name' => 'রায়গঞ্জ'],
            ['district_id' => '25', 'name' => 'শাহজাদপুর'],
            ['district_id' => '25', 'name' => 'সিরাজগঞ্জ সদর'],
            ['district_id' => '25', 'name' => 'তারাশ'],
            ['district_id' => '25', 'name' => 'উল্লাপাড়া'],
            ['district_id' => '26', 'name' => 'বিরামপুর'],
            ['district_id' => '26', 'name' => 'বীরগঞ্জ'],
            ['district_id' => '26', 'name' => 'বিরল'],
            ['district_id' => '26', 'name' => 'বোচাগঞ্জ'],
            ['district_id' => '26', 'name' => 'চিরিরবন্দর'],
            ['district_id' => '26', 'name' => 'ফুলবাড়ী'],
            ['district_id' => '26', 'name' => 'ঘোড়াঘাট'],
            ['district_id' => '26', 'name' => 'হাকিমপুর'],
            ['district_id' => '26', 'name' => 'কাহারোল'],
            ['district_id' => '26', 'name' => 'খানসামা'],
            ['district_id' => '26', 'name' => 'দিনাজপুর সদর'],
            ['district_id' => '26', 'name' => 'নবাবগঞ্জ'],
            ['district_id' => '26', 'name' => 'পার্বতীপুর'],
            ['district_id' => '27', 'name' => 'ফুলছড়ি'],
            ['district_id' => '27', 'name' => 'গাইবান্ধা সদর'],
            ['district_id' => '27', 'name' => 'গোবিন্দগঞ্জ'],
            ['district_id' => '27', 'name' => 'পলাশবাড়ী'],
            ['district_id' => '27', 'name' => 'সাদুল্লাপুর'],
            ['district_id' => '27', 'name' => 'সাঘাটা'],
            ['district_id' => '27', 'name' => 'সুন্দরগঞ্জ'],
            ['district_id' => '28', 'name' => 'ভুরুঙ্গামারী'],
            ['district_id' => '28', 'name' => 'চর রাজিবপুর'],
            ['district_id' => '28', 'name' => 'চিলমারী'],
            ['district_id' => '28', 'name' => 'ফুলবাড়ী'],
            ['district_id' => '28', 'name' => 'কুড়িগ্রাম সদর'],
            ['district_id' => '28', 'name' => 'নাগেশ্বরী'],
            ['district_id' => '28', 'name' => 'রাজারহাট'],
            ['district_id' => '28', 'name' => 'রৌমারী'],
            ['district_id' => '28', 'name' => 'উলিপুর'],
            ['district_id' => '29', 'name' => 'আদিতমারী'],
            ['district_id' => '29', 'name' => 'হাতীবান্ধা'],
            ['district_id' => '29', 'name' => 'কালীগঞ্জ'],
            ['district_id' => '29', 'name' => 'লালমনিরহাট সদর'],
            ['district_id' => '29', 'name' => 'পাটগ্রাম'],
            ['district_id' => '30', 'name' => 'ডিমলা'],
            ['district_id' => '30', 'name' => 'ডোমার'],
            ['district_id' => '30', 'name' => 'জলঢাকা'],
            ['district_id' => '30', 'name' => 'কিশোরগঞ্জ'],
            ['district_id' => '30', 'name' => 'নীলফামারী সদর'],
            ['district_id' => '30', 'name' => 'সৈয়দপুর'],

            ['district_id' => '31', 'name' => 'আটোয়ারী'],
            ['district_id' => '31', 'name' => 'বোদা'],
            ['district_id' => '31', 'name' => 'দেবীগঞ্জ'],
            ['district_id' => '31', 'name' => 'পঞ্চগড় সদর'],
            ['district_id' => '31', 'name' => 'তেতুলিয়া'],
            ['district_id' => '32', 'name' => 'বদরগঞ্জ'],
            ['district_id' => '32', 'name' => 'গঙ্গাচড়া'],
            ['district_id' => '32', 'name' => 'কাউনিয়া'],
            ['district_id' => '32', 'name' => 'রংপুর সদর'],
            ['district_id' => '32', 'name' => 'মিঠাপুকুর'],
            ['district_id' => '32', 'name' => 'পীরগাছা'],
            ['district_id' => '32', 'name' => 'পীরগঞ্জ'],
            ['district_id' => '32', 'name' => 'তারাগঞ্জ'],
            ['district_id' => '33', 'name' => 'বালিয়াডাঙ্গী'],
            ['district_id' => '33', 'name' => 'হরিপুর'],
            ['district_id' => '33', 'name' => 'পীরগঞ্জ'],
            ['district_id' => '33', 'name' => 'রানীসংকৈল'],
            ['district_id' => '33', 'name' => 'ঠাকুরগাঁও সদর'],
            ['district_id' => '34', 'name' => 'আমতলী'],
            ['district_id' => '34', 'name' => 'বামনা'],
            ['district_id' => '34', 'name' => 'বরগুনা সদর'],
            ['district_id' => '34', 'name' => 'বেতাগী'],
            ['district_id' => '34', 'name' => 'পাথরঘাটা'],
            ['district_id' => '34', 'name' => 'তালতলী'],
            ['district_id' => '35', 'name' => 'আগৈলঝাড়া'],
            ['district_id' => '35', 'name' => 'বাবুগঞ্জ'],
            ['district_id' => '35', 'name' => 'বাকেরগঞ্জ'],
            ['district_id' => '35', 'name' => 'বানারীপাড়া'],
            ['district_id' => '35', 'name' => 'গৌরনদী'],
            ['district_id' => '35', 'name' => 'হিজলা'],
            ['district_id' => '35', 'name' => 'বরিশাল সদর'],
            ['district_id' => '35', 'name' => 'মেহেন্দিগঞ্জ'],
            ['district_id' => '35', 'name' => 'মুলাদী'],
            ['district_id' => '35', 'name' => 'উজিরপুর'],
            ['district_id' => '36', 'name' => 'ভোলা সদর'],
            ['district_id' => '36', 'name' => 'বোরহানউদ্দিন'],
            ['district_id' => '36', 'name' => 'চরফ্যাশন'],
            ['district_id' => '36', 'name' => 'দৌলতখান'],
            ['district_id' => '36', 'name' => 'লালমোহন'],
            ['district_id' => '36', 'name' => 'মনপুরা'],
            ['district_id' => '36', 'name' => 'তজুমদ্দিন'],
            ['district_id' => '37', 'name' => 'ঝালকাঠি সদর'],
            ['district_id' => '37', 'name' => 'কাঠালিয়া'],
            ['district_id' => '37', 'name' => 'নলছিটি'],
            ['district_id' => '37', 'name' => 'রাজাপুর'],
            ['district_id' => '38', 'name' => 'বাউফল'],
            ['district_id' => '38', 'name' => 'দশমিনা'],
            ['district_id' => '38', 'name' => 'গলাচিপা'],
            ['district_id' => '38', 'name' => 'কলাপাড়া'],
            ['district_id' => '38', 'name' => 'মির্জাগঞ্জ'],
            ['district_id' => '38', 'name' => 'পটুয়াখালী সদর'],
            ['district_id' => '38', 'name' => 'রাঙ্গাবালী'],
            ['district_id' => '39', 'name' => 'ভান্ডারিয়া'],
            ['district_id' => '39', 'name' => 'কাউখালী'],
            ['district_id' => '39', 'name' => 'মঠবাড়িয়া'],
            ['district_id' => '39', 'name' => 'নাজিরপুর'],
            ['district_id' => '39', 'name' => 'পিরোজপুর সদর'],
            ['district_id' => '39', 'name' => 'নেসারাবাদ'],
            ['district_id' => '39', 'name' => 'জিয়ানগর'],
            ['district_id' => '40', 'name' => 'বান্দরবান সদর'],
            ['district_id' => '40', 'name' => 'থানচি'],
            ['district_id' => '40', 'name' => 'লামা'],
            ['district_id' => '40', 'name' => 'নাইক্ষ্যংছড়ি'],
            ['district_id' => '40', 'name' => 'আলীকদম'],
            ['district_id' => '40', 'name' => 'রোয়াংছড়ি'],
            ['district_id' => '40', 'name' => 'রুমা'],

            ['district_id' => '41', 'name' => 'ব্রাহ্মণবাড়িয়া সদর'],
            ['district_id' => '41', 'name' => 'আশুগঞ্জ'],
            ['district_id' => '41', 'name' => 'নাসিরনগর'],
            ['district_id' => '41', 'name' => 'নবীনগর'],
            ['district_id' => '41', 'name' => 'সরাইল'],
            ['district_id' => '41', 'name' => 'কসবা'],
            ['district_id' => '41', 'name' => 'আখাউড়া'],
            ['district_id' => '41', 'name' => 'বাঞ্ছারামপুর'],
            ['district_id' => '41', 'name' => 'বিজয়নগর'],
            ['district_id' => '42', 'name' => 'চাঁদপুর সদর'],
            ['district_id' => '42', 'name' => 'ফরিদগঞ্জ'],
            ['district_id' => '42', 'name' => 'হাইমচর'],
            ['district_id' => '42', 'name' => 'হাজীগঞ্জ'],
            ['district_id' => '42', 'name' => 'কচুয়া'],
            ['district_id' => '42', 'name' => 'মতলব দক্ষিণ'],
            ['district_id' => '42', 'name' => 'মতলব উত্তর'],
            ['district_id' => '42', 'name' => 'শাহরাস্তি'],
            ['district_id' => '43', 'name' => 'আনোয়ারা'],
            ['district_id' => '43', 'name' => 'বাঁশখালী'],
            ['district_id' => '43', 'name' => 'বোয়ালখালী'],
            ['district_id' => '43', 'name' => 'চন্দনাইশ'],
            ['district_id' => '43', 'name' => 'ফটিকছড়ি'],
            ['district_id' => '43', 'name' => 'হাটহাজারী'],
            ['district_id' => '43', 'name' => 'লোহাগাড়া'],
            ['district_id' => '43', 'name' => 'মীরসরাই'],
            ['district_id' => '43', 'name' => 'পটিয়া'],
            ['district_id' => '43', 'name' => 'রাঙ্গুনিয়া'],
            ['district_id' => '43', 'name' => 'রাউজান'],
            ['district_id' => '43', 'name' => 'সন্দ্বীপ'],
            ['district_id' => '43', 'name' => 'সাতকানিয়া'],
            ['district_id' => '43', 'name' => 'সীতাকুণ্ড'],
            ['district_id' => '44', 'name' => 'বরুড়া'],
            ['district_id' => '44', 'name' => 'ব্রাহ্মণপাড়া'],
            ['district_id' => '44', 'name' => 'বুড়িচং'],
            ['district_id' => '44', 'name' => 'চান্দিনা'],
            ['district_id' => '44', 'name' => 'চৌদ্দগ্রাম'],
            ['district_id' => '44', 'name' => 'দাউদকান্দি'],
            ['district_id' => '44', 'name' => 'দেবিদ্বার'],
            ['district_id' => '44', 'name' => 'হোমনা'],
            ['district_id' => '44', 'name' => 'কুমিল্লা সদর'],
            ['district_id' => '44', 'name' => 'লাকসাম'],
            ['district_id' => '44', 'name' => 'মনোহরগঞ্জ'],
            ['district_id' => '44', 'name' => 'মেঘনা'],
            ['district_id' => '44', 'name' => 'মুরাদনগর'],
            ['district_id' => '44', 'name' => 'নাঙ্গলকোট'],
            ['district_id' => '44', 'name' => 'তিতাস'],
            ['district_id' => '45', 'name' => 'চকরিয়া'],
            ['district_id' => '45', 'name' => 'কক্সবাজার সদর'],
            ['district_id' => '45', 'name' => 'কুতুবদিয়া'],
            ['district_id' => '45', 'name' => 'মহেশখালী'],
            ['district_id' => '45', 'name' => 'রামু'],
            ['district_id' => '45', 'name' => 'টেকনাফ'],
            ['district_id' => '45', 'name' => 'উখিয়া'],
            ['district_id' => '45', 'name' => 'পেকুয়া'],
            ['district_id' => '46', 'name' => 'ফেনী সদর'],
            ['district_id' => '46', 'name' => 'ছাগলনাইয়া'],
            ['district_id' => '46', 'name' => 'দাগনভূঞা'],
            ['district_id' => '46', 'name' => 'পরশুরাম'],
            ['district_id' => '46', 'name' => 'সোনাগাজী'],
            ['district_id' => '46', 'name' => 'ফুলগাজী'],
            ['district_id' => '47', 'name' => 'দীঘিনালা'],
            ['district_id' => '47', 'name' => 'খাগড়াছড়ি সদর'],
            ['district_id' => '47', 'name' => 'লক্ষীছড়ি'],
            ['district_id' => '47', 'name' => 'মহালছড়ি'],
            ['district_id' => '47', 'name' => 'মানিকছড়ি'],
            ['district_id' => '47', 'name' => 'মাটিরাঙ্গা'],
            ['district_id' => '47', 'name' => 'পানছড়ি'],
            ['district_id' => '47', 'name' => 'রামগড়'],
            ['district_id' => '48', 'name' => 'লক্ষ্মীপুর সদর'],
            ['district_id' => '48', 'name' => 'রায়পুর'],
            ['district_id' => '48', 'name' => 'রামগঞ্জ'],
            ['district_id' => '48', 'name' => 'রামগতি'],
            ['district_id' => '48', 'name' => 'কমলনগর'],
            ['district_id' => '49', 'name' => 'বেগমগঞ্জ'],
            ['district_id' => '49', 'name' => 'নোয়াখালী সদর'],
            ['district_id' => '49', 'name' => 'চাটখিল'],
            ['district_id' => '49', 'name' => 'কোম্পানীগঞ্জ'],
            ['district_id' => '49', 'name' => 'হাতিয়া'],
            ['district_id' => '49', 'name' => 'সেনবাগ'],
            ['district_id' => '49', 'name' => 'সোনাইমুড়ি'],
            ['district_id' => '49', 'name' => 'সুবর্ণচর'],
            ['district_id' => '50', 'name' => 'রাঙামাটি সদর'],
            ['district_id' => '50', 'name' => 'বেলাইছড়ি'],
            ['district_id' => '50', 'name' => 'বাঘাইছড়ি'],
            ['district_id' => '50', 'name' => 'বরকল'],
            ['district_id' => '50', 'name' => 'জুরাছড়ি'],
            ['district_id' => '50', 'name' => 'রাজস্থলী'],
            ['district_id' => '50', 'name' => 'কাপ্তাই'],
            ['district_id' => '50', 'name' => 'লংগদু'],
            ['district_id' => '50', 'name' => 'নানিয়ারচর'],
            ['district_id' => '50', 'name' => 'কাউখালী'],

            ['district_id' => '51', 'name' => 'আজমিরীগঞ্জ'],
            ['district_id' => '51', 'name' => 'বানিয়াচং'],
            ['district_id' => '51', 'name' => 'বাহুবল'],
            ['district_id' => '51', 'name' => 'চুনারুঘাট'],
            ['district_id' => '51', 'name' => 'হবিগঞ্জ সদর'],
            ['district_id' => '51', 'name' => 'লাখাই'],
            ['district_id' => '51', 'name' => 'মাধবপুর'],
            ['district_id' => '51', 'name' => 'নবীগঞ্জ'],

            ['district_id' => '52', 'name' => 'বড়লেখা'],
            ['district_id' => '52', 'name' => 'কামালগঞ্জ'],
            ['district_id' => '52', 'name' => 'কুলাউড়া'],
            ['district_id' => '52', 'name' => 'মৌলভীবাজার সদর'],
            ['district_id' => '52', 'name' => 'রাজনগর'],
            ['district_id' => '52', 'name' => 'শ্রীমঙ্গল'],
            ['district_id' => '52', 'name' => 'জুড়ী'],

            ['district_id' => '53', 'name' => 'বিশ্বাম্বরপুর'],
            ['district_id' => '53', 'name' => 'ছাতক'],
            ['district_id' => '53', 'name' => 'দেড়াই'],
            ['district_id' => '53', 'name' => 'ধরমপাশা'],
            ['district_id' => '53', 'name' => 'দৌরাবাজার'],
            ['district_id' => '53', 'name' => 'যাগন্নাথপুর'],
            ['district_id' => '53', 'name' => 'জামালগঞ্জ'],
            ['district_id' => '53', 'name' => 'সুন্দ'],
            ['district_id' => '53', 'name' => 'সুনামগঞ্জ সদর'],
            ['district_id' => '53', 'name' => 'তাহিরপুর'],

            ['district_id' => '54', 'name' => 'বালাগঞ্জ'],
            ['district_id' => '54', 'name' => 'বিয়ানীবাজার'],
            ['district_id' => '54', 'name' => 'বিশ্বনাথ'],
            ['district_id' => '54', 'name' => 'কম্পানিগঞ্জ'],
            ['district_id' => '54', 'name' => 'ফেঞ্চুগঞ্জ'],
            ['district_id' => '54', 'name' => 'গুলাপগঞ্জ'],
            ['district_id' => '54', 'name' => 'গোয়াইনঘাট'],
            ['district_id' => '54', 'name' => 'জৈন্তাপুর'],
            ['district_id' => '54', 'name' => 'কানাইঘাট'],
            ['district_id' => '54', 'name' => 'সিলেট সদর'],
            ['district_id' => '54', 'name' => 'জকিগঞ্জ'],

            ['district_id' => '55', 'name' => 'বাগেরহাট সদর'],
            ['district_id' => '55', 'name' => 'চিতলমারি'],
            ['district_id' => '55', 'name' => 'ফকিরহাট'],
            ['district_id' => '55', 'name' => 'কচুয়া'],
            ['district_id' => '55', 'name' => 'মোল্লাহাট'],
            ['district_id' => '55', 'name' => 'মংলা'],
            ['district_id' => '55', 'name' => 'মোরেলগঞ্জ'],
            ['district_id' => '55', 'name' => 'রামপাল'],
            ['district_id' => '55', 'name' => 'সারংখোলা'],

            ['district_id' => '56', 'name' => 'চুয়াডাঙ্গা সদর'],
            ['district_id' => '56', 'name' => 'আলমডাঙ্গা'],
            ['district_id' => '56', 'name' => 'দামুরহুদা'],
            ['district_id' => '56', 'name' => 'জীবননগর'],

            ['district_id' => '57', 'name' => 'অভয়নগর'],
            ['district_id' => '57', 'name' => 'বাঘেরপাড়া'],
            ['district_id' => '57', 'name' => 'চৌগাছা'],
            ['district_id' => '57', 'name' => 'ঝিকরগাছা'],
            ['district_id' => '57', 'name' => 'কেশবপুর'],
            ['district_id' => '57', 'name' => 'যশোর সদর'],
            ['district_id' => '57', 'name' => 'মনিরামপুর'],
            ['district_id' => '57', 'name' => 'শার্শা'],

            ['district_id' => '58', 'name' => 'হরিনাকুন্ডা'],
            ['district_id' => '58', 'name' => 'ঝিনাইদহ সদর'],
            ['district_id' => '58', 'name' => 'কালীগঞ্জ'],
            ['district_id' => '58', 'name' => 'কোটচাঁদপুর'],
            ['district_id' => '58', 'name' => 'মহেশপুর'],
            ['district_id' => '58', 'name' => 'শৈলকুপা'],

            ['district_id' => '59', 'name' => 'বাটিয়াঘাটা'],
            ['district_id' => '59', 'name' => 'দাকোপ'],
            ['district_id' => '59', 'name' => 'ডুমুরিয়া'],
            ['district_id' => '59', 'name' => 'দিঘলিয়া'],
            ['district_id' => '59', 'name' => 'কয়রা'],
            ['district_id' => '59', 'name' => 'পাইকগাছা'],
            ['district_id' => '59', 'name' => 'ফুলতলা'],
            ['district_id' => '59', 'name' => 'রূপসা'],
            ['district_id' => '59', 'name' => 'তেরখাদা'],


            ['district_id' => '60', 'name' => 'কুষ্টিয়া সদর'],
            ['district_id' => '60', 'name' => 'কুমারখালী'],
            ['district_id' => '60', 'name' => 'খোকসা'],
            ['district_id' => '60', 'name' => 'মিরপুর'],
            ['district_id' => '60', 'name' => 'দৌলতপুর'],
            ['district_id' => '60', 'name' => 'ভেরামারা'],

            ['district_id' => '61', 'name' => 'মাগুরা সদর'],
            ['district_id' => '61', 'name' => 'মোহাম্মদপুর'],
            ['district_id' => '61', 'name' => 'শালিখা'],
            ['district_id' => '61', 'name' => 'শ্রীপুর'],

            ['district_id' => '62', 'name' => 'গাংনী'],
            ['district_id' => '62', 'name' => 'মুজিবনগর'],
            ['district_id' => '62', 'name' => 'মেহেরপুর সদর'],

            ['district_id' => '63', 'name' => 'কালিয়া'],
            ['district_id' => '63', 'name' => 'লোহাগাড়া'],
            ['district_id' => '63', 'name' => 'নড়াইল সদর'],

            ['district_id' => '64', 'name' => 'আসসানী'],
            ['district_id' => '64', 'name' => 'দেবহাটা'],
            ['district_id' => '64', 'name' => 'কালরোয়া'],
            ['district_id' => '64', 'name' => 'সাতক্ষীরা সদর'],
            ['district_id' => '64', 'name' => 'শ্যামনগর'],
            ['district_id' => '64', 'name' => 'তালা'],

        ];

        foreach ($subDistricts as $subDistrict) {
            SubDistrict::create($subDistrict);
        }
    }
}
